[build]
#target = "wasm32-unknown-unknown"
target = "x86_64-unknown-linux-gnu"
rustflags = ["-C", "target-feature=+atomics,+bulk-memory,+mutable-globals"]

[unstable]
build-std = ['std', 'panic_abort']